name: Build & Deploy

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing packages
        run: npm install
      
      - name: Setup Git
        run: |
         git config --global user.email "banti@gheneti.com"
         git config --global user.name "Banti Gheneti"

      - name: Build Gridsome site
        run: npm run build
      
      - name: deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
